version: '3.8'

services:      
  django:
    build: ./backend
    container_name: django-backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./backend/:/srv/app
      - ./media:/srv/app/media