version: '3.3'

services:      
  django:
    build: ./backend
    container_name: django-backend
    ports:
      - 8000:8000
    restart: always
    volumes:
      - ./../config:/app/backend/config
      - ./../media:/app/backend/media
      - ./../static:/app/backend/static
    depends_on:
      - postgres
  react:
    build: ./frontend
    container_name: react-frontend
    ports:
      - 3000:3000
    restart: always
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - django
  postgres:
    image: postgres:16.1-alpine
    container_name: postgres-db
    ports:
      - 5432:5432            
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/data/postgres"
    volumes:
      - ./../db:/data/postgres
  nginx:
    build: ./nginx
    container_name: nginx-server
    ports:
      - 80:80
    restart: always
    volumes:
      - ./../static:/app/backend/static
      - ./../media:/app/backend/media
    depends_on:
      - django
      - react
      - postgres

volumes:
  media:
  static: