version: '3.8'

services:      
  django:
    build: ./backend
    container_name: django-backend
    ports:
      - 8000:8000
    restart: always
    volumes:
      - ./../config:/app/backend/config
      - ./../media:/app/backend/media
      - ./../static:/app/backend/static
      - ./../db:/app/backend/db
  react:
    build: ./frontend
    container_name: react-frontend
    ports:
      - 3000:3000
    restart: always
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - django
  nginx:
    build: ./nginx
    container_name: nginx-server
    ports:
      - 80:80
    restart: always
    volumes:
      - ./../static:/app/backend/static
      - ./../media:/app/backend/media
    depends_on:
      - django
      - react

volumes:
  media:
  static: